version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./client:/app
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000

  server:
    build:
      context: ./server
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./server:/app
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 4000:4000

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 6500:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready', '-U', 'postgres', '-d', 'bbms']
      retries: 3
      timeout: 5s
    user: postgres
    environment:
      POSTGRES_DB: bbms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
