version: '3'
services:
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
    working_dir: /app
    command: yarn dev
    ports:
      - 3000:3000

  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
    working_dir: /app
    command: yarn start:dev
    ports:
      - 4000:4000
